/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DemoPassportRouteImport } from './routes/demo.passport'
import { Route as DemoJoinRouteImport } from './routes/demo.join'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AdminUpdatePasswordRouteImport } from './routes/admin.update-password'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as DemoCheckinVenueIdRouteImport } from './routes/demo.checkin.$venueId'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin.events.$eventId'
import { Route as AdminEventsEventIdPreviewRouteImport } from './routes/admin_.events.$eventId.preview'
import { Route as AdminEventsEventIdBrandingRouteImport } from './routes/admin.events.$eventId_.branding'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoPassportRoute = DemoPassportRouteImport.update({
  id: '/demo/passport',
  path: '/demo/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoJoinRoute = DemoJoinRouteImport.update({
  id: '/demo/join',
  path: '/demo/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUpdatePasswordRoute = AdminUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoCheckinVenueIdRoute = DemoCheckinVenueIdRouteImport.update({
  id: '/demo/checkin/$venueId',
  path: '/demo/checkin/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdPreviewRoute =
  AdminEventsEventIdPreviewRouteImport.update({
    id: '/admin_/events/$eventId/preview',
    path: '/admin/events/$eventId/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdBrandingRoute =
  AdminEventsEventIdBrandingRouteImport.update({
    id: '/events/$eventId_/branding',
    path: '/events/$eventId/branding',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/update-password': typeof AdminUpdatePasswordRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/demo/join': typeof DemoJoinRoute
  '/demo/passport': typeof DemoPassportRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/demo/checkin/$venueId': typeof DemoCheckinVenueIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/branding': typeof AdminEventsEventIdBrandingRoute
  '/admin/events/$eventId/preview': typeof AdminEventsEventIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/update-password': typeof AdminUpdatePasswordRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/demo/join': typeof DemoJoinRoute
  '/demo/passport': typeof DemoPassportRoute
  '/admin': typeof AdminIndexRoute
  '/demo': typeof DemoIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/demo/checkin/$venueId': typeof DemoCheckinVenueIdRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/branding': typeof AdminEventsEventIdBrandingRoute
  '/admin/events/$eventId/preview': typeof AdminEventsEventIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/update-password': typeof AdminUpdatePasswordRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/demo/join': typeof DemoJoinRoute
  '/demo/passport': typeof DemoPassportRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/demo/checkin/$venueId': typeof DemoCheckinVenueIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/$eventId_/branding': typeof AdminEventsEventIdBrandingRoute
  '/admin_/events/$eventId/preview': typeof AdminEventsEventIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/signup'
    | '/support'
    | '/admin/account'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/system'
    | '/admin/update-password'
    | '/admin/venues'
    | '/demo/join'
    | '/demo/passport'
    | '/admin/'
    | '/demo/'
    | '/admin/events/$eventId'
    | '/demo/checkin/$venueId'
    | '/admin/events/'
    | '/admin/events/$eventId/branding'
    | '/admin/events/$eventId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/signup'
    | '/support'
    | '/admin/account'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/system'
    | '/admin/update-password'
    | '/admin/venues'
    | '/demo/join'
    | '/demo/passport'
    | '/admin'
    | '/demo'
    | '/admin/events/$eventId'
    | '/demo/checkin/$venueId'
    | '/admin/events'
    | '/admin/events/$eventId/branding'
    | '/admin/events/$eventId/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/signup'
    | '/support'
    | '/admin/account'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/system'
    | '/admin/update-password'
    | '/admin/venues'
    | '/demo/join'
    | '/demo/passport'
    | '/admin/'
    | '/demo/'
    | '/admin/events/$eventId'
    | '/demo/checkin/$venueId'
    | '/admin/events/'
    | '/admin/events/$eventId_/branding'
    | '/admin_/events/$eventId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  DemoJoinRoute: typeof DemoJoinRoute
  DemoPassportRoute: typeof DemoPassportRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoCheckinVenueIdRoute: typeof DemoCheckinVenueIdRoute
  AdminEventsEventIdPreviewRoute: typeof AdminEventsEventIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/passport': {
      id: '/demo/passport'
      path: '/demo/passport'
      fullPath: '/demo/passport'
      preLoaderRoute: typeof DemoPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/join': {
      id: '/demo/join'
      path: '/demo/join'
      fullPath: '/demo/join'
      preLoaderRoute: typeof DemoJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/update-password': {
      id: '/admin/update-password'
      path: '/update-password'
      fullPath: '/admin/update-password'
      preLoaderRoute: typeof AdminUpdatePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/checkin/$venueId': {
      id: '/demo/checkin/$venueId'
      path: '/demo/checkin/$venueId'
      fullPath: '/demo/checkin/$venueId'
      preLoaderRoute: typeof DemoCheckinVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/events/$eventId/preview': {
      id: '/admin_/events/$eventId/preview'
      path: '/admin/events/$eventId/preview'
      fullPath: '/admin/events/$eventId/preview'
      preLoaderRoute: typeof AdminEventsEventIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId_/branding': {
      id: '/admin/events/$eventId_/branding'
      path: '/events/$eventId/branding'
      fullPath: '/admin/events/$eventId/branding'
      preLoaderRoute: typeof AdminEventsEventIdBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUpdatePasswordRoute: typeof AdminUpdatePasswordRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEventIdBrandingRoute: typeof AdminEventsEventIdBrandingRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUpdatePasswordRoute: AdminUpdatePasswordRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEventIdBrandingRoute: AdminEventsEventIdBrandingRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  DemoJoinRoute: DemoJoinRoute,
  DemoPassportRoute: DemoPassportRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoCheckinVenueIdRoute: DemoCheckinVenueIdRoute,
  AdminEventsEventIdPreviewRoute: AdminEventsEventIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
